### ISSUE TITLE
AssertionError when try to run predict.py

### ISSUE THREAD

**Issue by Jusya** [lachlants/denet#3]
Hello,
I'v never worked with Theano before, so I just installed the GitHub version you provided and tried to run predict.py via Anaconda and also through shell script  model-predict with your pretrained model. I get an assertion error problem:
Failure
Traceback (most recent call last):
  File "/home/yulia/anaconda3/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/home/yulia/anaconda3/lib/python3.6/unittest/case.py", line 601, in run
    testMethod()
  File "/home/yulia/anaconda3/lib/python3.6/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/home/yulia/anaconda3/lib/python3.6/site-packages/nose/loader.py", line 417, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/yulia/anaconda3/lib/python3.6/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/yulia/anaconda3/lib/python3.6/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/yulia/anaconda3/lib/python3.6/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/home/yulia/anaconda3/lib/python3.6/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 675, in _load
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "/home/yulia/PycharmProjects/denet/denet/model/predict.py", line 14, in <module>
    import denet.model.model_cnn as model_cnn
  File "/home/yulia/PycharmProjects/denet/denet/model/model_cnn.py", line 18, in <module>
    from denet.layer.layer_types import layer_types
  File "/home/yulia/PycharmProjects/denet/denet/layer/layer_types.py", line 23, in <module>
    from denet.layer.denet_sparse import DeNetSparseLayer
  File "/home/yulia/PycharmProjects/denet/denet/layer/denet_sparse.py", line 19, in <module>
    assert not c_code is None
AssertionError
F
FAIL: Failure: AssertionError ()
Traceback (most recent call last):
  File "/home/yulia/anaconda3/lib/python3.6/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/home/yulia/anaconda3/lib/python3.6/site-packages/nose/loader.py", line 417, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/yulia/anaconda3/lib/python3.6/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/yulia/anaconda3/lib/python3.6/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/yulia/anaconda3/lib/python3.6/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/home/yulia/anaconda3/lib/python3.6/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 675, in _load
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "/home/yulia/PycharmProjects/denet/denet/model/predict.py", line 14, in <module>
    import denet.model.model_cnn as model_cnn
  File "/home/yulia/PycharmProjects/denet/denet/model/model_cnn.py", line 18, in <module>
    from denet.layer.layer_types import layer_types
  File "/home/yulia/PycharmProjects/denet/denet/layer/layer_types.py", line 23, in <module>
    from denet.layer.denet_sparse import DeNetSparseLayer
  File "/home/yulia/PycharmProjects/denet/denet/layer/denet_sparse.py", line 19, in <module>
    assert not c_code is None
AssertionError
Ran 1 test in 0.011s
FAILED (failures=1)
Process finished with exit code 1

I walked through debugger and here is the code where it throws an exception:

`def import_c(fname):
    # import logging
    # logging.getLogger("theano.gof.cmodule").setLevel(logging.DEBUG)

    #compile code
    import theano
    import theano.gof.cmodule as cmodule
    import theano.gof.compilelock as compilelock
    from theano.gof.utils import hash_from_code
    compilelock.get_lock()
    try:
        compile_args = ["-std=c++11", "-fPIC", "-O3", "-fno-math-errno", "-Wno-unused-label", "-Wno-unused-variable", "-Wno-write-strings"]
        compile_dir = cmodule.dlimport_workdir(theano.config.compiledir)
        with open(fname, "r") as f:
            compile_code = f.read()

        compile_hash = os.path.basename(os.path.splitext(fname)[0])
        **cmodule_import = cmodule.GCC_compiler.compile_str(compile_hash, compile_code, compile_dir, preargs = compile_args)**
    except Exception as e:
        print("Warning: Failed to compile cmodule:", e)
        cmodule_import = None
    finally:
        compilelock.release_lock()

    return cmodule_import`

On this line `cmodule_import = cmodule.GCC_compiler.compile_str(compile_hash, compile_code, compile_dir, preargs = compile_args)`

Hope, you can help me with this issue. Thank you in advance)

**Comment by lachlants** [comment]
Hello,

Hmmmm looks like it's failing to compile the c code that is supplied with denet_sparse (i.e. layers/denet_sparse.cc) . Can you please supply stdout and stderr logs? For some reason Theano logs most compile errors in stdout.

**Comment by Jusya** [comment]
Can you please help to find out where can I get those stdout and stderr logs? I looked up in the Internet something like import sys, sys.stdout, and sys.stderr, but i can't figure out whether it is right to use them and how to use them)

**Comment by lachlants** [comment]
No worries, assuming your using bash just run your command like this: `bin/model-predict .... > log.out 2> log.err`

This will redirect the stdout and stderr buffers to the files "log.out" and "log.err" in the current directory

**Comment by Jusya** [comment]
Thank you for helping me) I ran this command from denet/bin/ directory:

sh model-predict --batch-size 8 --thread-num 4 --predict-mode detect,voc --input VOC /home/yulia/PycharmProjects/PASCAL\ VOC/VOC2007\ test/VOC2007/JPEGImages/ --model /home/yulia/PycharmProjects/denet/models/voc2007/merged.mdl --extension voc,2007-test,images_per_subset=128,crop=512,scale_mode=large > log.out 2> log.err

Then I got log.out file with content:

Warning: Failed to compile cmodule: /home/yulia/.theano/compiledir_Linux-4.4--generic-x86_64-with-debian-stretch-sid-x86_64-3.6.1-64/tmpq6nucnue/denet_sparse.so: undefined symbol: _ZNSt6thread15_M_start_threadESt10shared_ptrINS_10_Impl_baseEEPFvvE

And for log.err:

dirname: missing operand
Try 'dirname --help' for more information.
model-predict: 3: model-predict: source: not found
Traceback (most recent call last):
  File "/home/yulia/PycharmProjects/denet/denet/model/predict.py", line 14, in <module>
    import denet.model.model_cnn as model_cnn
  File "/home/yulia/PycharmProjects/denet/denet/model/model_cnn.py", line 18, in <module>
    from denet.layer.layer_types import layer_types
  File "/home/yulia/PycharmProjects/denet/denet/layer/layer_types.py", line 23, in <module>
    from denet.layer.denet_sparse import DeNetSparseLayer
  File "/home/yulia/PycharmProjects/denet/denet/layer/denet_sparse.py", line 19, in <module>
    assert not c_code is None
AssertionError

**Comment by lachlants** [comment]
Hmmm looks like it failing to find the source code "denet/layers/denet_sparse.cc". 

Looking at "denet/layer/denet_sparse.py" find the line:

`c_code = common.import_c(os.path.join(os.path.dirname(__file__), "denet_sparse.cc"))`

The argument to common.import_c() is the path its looking at. Could you please print out the path e.g. modify the above line to:

`fname = os.path.join(os.path.dirname(__file__), "denet_sparse.cc")`
`print("Filename:", fname)`
`c_code = common.import_c(fname)`

and rerun the command. My guess is that it's not getting the path of the current file properly... possibly due to spaces in the path. 

Also your going to want to specify a GPU for the command to work properly (the code doesn't support CPU execution). e.g. "GPU=0 sh model-predict ..."

**Comment by Jusya** [comment]
I ran previous command with addition GPU=0 at the beginning and printed fname, so the log.out:
Filename: /home/yulia/PycharmProjects/denet/denet/layer/denet_sparse.cc
Warning: Failed to compile cmodule: /home/yulia/.theano/compiledir_Linux-4.4--generic-x86_64-with-debian-stretch-sid-x86_64-3.6.1-64/tmpsg38tvyt/denet_sparse.so: undefined symbol: _ZNSt6thread15_M_start_threadESt10shared_ptrINS_10_Impl_baseEEPFvvE

and the log.err is:
dirname: missing operand
Try 'dirname --help' for more information.
model-predict: 3: model-predict: source: not found
Traceback (most recent call last):
  File "/home/yulia/PycharmProjects/denet/denet/model/predict.py", line 14, in <module>
    import denet.model.model_cnn as model_cnn
  File "/home/yulia/PycharmProjects/denet/denet/model/model_cnn.py", line 18, in <module>
    from denet.layer.layer_types import layer_types
  File "/home/yulia/PycharmProjects/denet/denet/layer/layer_types.py", line 23, in <module>
    from denet.layer.denet_sparse import DeNetSparseLayer
  File "/home/yulia/PycharmProjects/denet/denet/layer/denet_sparse.py", line 21, in <module>
    assert not c_code is None
AssertionError

This path (Filename: /home/yulia/PycharmProjects/denet/denet/layer/denet_sparse.cc) seems to be valid, I can reach the file via file manager.

**Comment by lachlants** [comment]
Hmmm OK thats pretty confusing. Looks like its breaking during the linking phase... it's failing to find an std::thread function which is part of the standard library in c++11. From what I've read Anaconda installs it's own c standard library, so you might have a version mismatch. Can you print the "PATH", "LD_LIBRARY_PATH", "LIBRARY_PATH" environment variables e.g. run the following commands in bash:

`echo $PATH`
`echo $LD_LIBRARY_PATH`
`echo $LIBRARY_PATH`

My guess is that anaconda is messing with one of these variables and causing the compiler and linked library to be different versions.

**Comment by Jusya** [comment]
Thank you for still helping me) 

yulia@yulia_host:~$ echo $PATH
/home/yulia/anaconda3/bin:/home/yulia/bin:/home/yulia/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
yulia@yulia_host:~$ echo $LD_LIBRARY_PATH
/usr/local/cuda/lib64:/usr/local/cuda/extras/CUPTI/lib64:
yulia@yulia_host:~$ echo $LIBRARY_PATH

yulia@yulia_host:~$

**Comment by lachlants** [comment]
Try removing the anaconda3 directory from $PATH. e.g. in bash write
`export PATH=/home/yulia/bin:/home/yulia/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin`

Then delete the theano cache (located at ~/.theano/) and try the the command again. 

You can check which python3 and gcc are being used via:
```
which python3
which gcc
```
Make sure they don't point to anything in the anaconda distribution.

**Comment by Jusya** [comment]
Hello, I'm sorry for being absent for a while) I've removed anaconda from $PATH:

yulia@yulia_host:~/PycharmProjects/denet$ echo $PATH
/home/yulia/bin:/home/yulia/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin

so which python3 gives me:
yulia@yulia_host:~/PycharmProjects/denet$ which python3
/usr/bin/python3

and which gcc:
yulia@yulia_host:~/PycharmProjects/denet$ which gcc
/usr/bin/gcc

Installed Theano for the /usr/bin/python3 so:
yulia@yulia_host:~/PycharmProjects/denet$ pip3 list
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
beautifulsoup4 (4.4.1)
catfish (1.4.2)
chardet (2.3.0)
command-not-found (0.3)
defer (1.0.6)
html5lib (0.999)
language-selector (0.1)
lightdm-gtk-greeter-settings (1.2.1)
lxml (3.5.0)
menulibre (2.1.3)
mugshot (0.3.1)
onboard (1.2.0)
pexpect (4.0.1)
Pillow (3.1.2)
pip (9.0.1)
psutil (3.4.2)
ptyprocess (0.5)
pycups (1.9.73)
pycurl (7.43.0)
pygobject (3.20.0)
python-apt (1.1.0b1)
python-debian (0.1.27)
python-systemd (231)
pyxdg (0.25)
reportlab (3.3.0)
requests (2.9.1)
screen-resolution-extra (0.0.0)
sessioninstaller (0.0.0)
setuptools (28.8.0)
six (1.10.0)
Theano (0.9.0.dev5, /home/yulia/Theano)
ubuntu-drivers-common (0.0.0)
ufw (0.35)
unattended-upgrades (0.1)
urllib3 (1.13.1)
wheel (0.29.0)
xkit (0.0.0)

Deleted everything from ~/theano/ so it is empty now.

Then I've tried to run the command:
GPU=0 sh bin/model-predict --batch-size 8 --thread-num 4 --predict-mode detect,voc --input VOC /home/yulia/PycharmProjects/PASCAL\ VOC/VOC2007\ test/VOC2007/JPEGImages/ --model /home/yulia/PycharmProjects/denet/models/voc2007/merged.mdl --extension voc,2007-test,images_per_subset=128,crop=512,scale_mode=large > log.out 2> log.err

again, but I get this message in log.out:
Filename: /home/yulia/PycharmProjects/denet/denet/layer/denet_sparse.cc
Warning: Failed to compile cmodule: /home/yulia/.theano/compiledir_Linux-4.4--generic-x86_64-with-debian-stretch-sid-x86_64-3.6.1-64/tmpsg38tvyt/denet_sparse.so: undefined symbol: _ZNSt6thread15_M_start_threadESt10shared_ptrINS_10_Impl_baseEEPFvvE

and in log.err:
dirname: missing operand
Try 'dirname --help' for more information.
model-predict: 3: model-predict: source: not found
Traceback (most recent call last):
  File "/home/yulia/PycharmProjects/denet/denet/model/predict.py", line 14, in <module>
    import denet.model.model_cnn as model_cnn
  File "/home/yulia/PycharmProjects/denet/denet/model/model_cnn.py", line 18, in <module>
    from denet.layer.layer_types import layer_types
  File "/home/yulia/PycharmProjects/denet/denet/layer/layer_types.py", line 23, in <module>
    from denet.layer.denet_sparse import DeNetSparseLayer
  File "/home/yulia/PycharmProjects/denet/denet/layer/denet_sparse.py", line 21, in <module>
    assert not c_code is None
AssertionError

And also, now it is no files are created in ~/.theano/ directory after I ran the shell script model-predict, but they used to be created before :(

**Comment by lachlants** [comment]
Hello, I'm somewhat running out of ideas. Have you tried any other Theano examples with your installation?

You can enable more debugging info by going to the function `import_c()` in `denet/common/__init__.py` and uncommenting the two lines at the top.... then rerunning the code. This will show us the commands that were used to compile the C code. Not sure if it will help but you can also try adding `"-D_GLIBCXX_USE_CXX11_ABI=0"` to the `compile_args` list in `import_c()`. 

Also, can you send me the output of `gcc --version` and the lines that are printed when you start python3 in interactive mode.

**Comment by Jusya** [comment]
Hello) Finally, using all you answers, it looks like I managed to run model-predict on VOC 2007 test, there was a complex problem of my unfamiliarity with Theano and different console stuff, but now, I see that the script is still working and log.out file grows with messages like:

Average FPS=0.8
Using detection params - pr threshold: 0.010000, nms threshold: 0.500000, corner_threshold: 0.010000, corner_max: 1024
Detecting sample bboxs (0.01)
Took 8634 ms to get_samples (8623 model, 11 build, 1024 max corners)
Found sample bboxs: [0, 0, 0, 0, 0, 0, 0, 0]
Found detections: [0, 0, 0, 0, 0, 0, 0, 0]
FPS=0.8, Timing (ms) - get samples: 8635, upload: 0, classify: 978, build+nms 0
Average FPS=0.8
Using detection params - pr threshold: 0.010000, nms threshold: 0.500000, corner_threshold: 0.010000, corner_max: 1024
Detecting sample bboxs (0.01)
Took 8721 ms to get_samples (8716 model, 4 build, 1024 max corners)
Found sample bboxs: [0, 0, 0, 0, 0, 0, 0, 0]

Is it Ok to have these messages when there is nothing appear in the "results" directory?)

Huge "thank you" for you help :)

**Comment by lachlants** [comment]
Thats great! It appears to be compiling the C extension modules properly... however it's not using the GPU. That's why the FPS is really low and your not getting any sample_bboxs / detections. Did you specify the GPU=N variable before the command? You should see some GPU allocation info in the log.err file.

**Comment by Jusya** [comment]
Hello) I ran the model-predict on GPU and got following results:

aeroplane - AP: 0.7942 (681 detections,  311 groundtruth, 285 non difficult)
bicycle - AP: 0.8130 (994 detections,  389 groundtruth, 337 non difficult)
bird - AP: 0.7873 (1121 detections,  576 groundtruth, 459 non difficult)
boat - AP: 0.6934 (1192 detections,  393 groundtruth, 263 non difficult)
bottle - AP: 0.5948 (1512 detections,  657 groundtruth, 469 non difficult)
bus - AP: 0.8648 (890 detections,  254 groundtruth, 213 non difficult)
car - AP: 0.8630 (3519 detections,  1541 groundtruth, 1201 non difficult)
cat - AP: 0.8629 (600 detections,  370 groundtruth, 358 non difficult)
chair - AP: 0.5828 (3984 detections,  1374 groundtruth, 756 non difficult)
cow - AP: 0.8213 (829 detections,  329 groundtruth, 244 non difficult)
diningtable - AP: 0.7225 (1545 detections,  299 groundtruth, 206 non difficult)
dog - AP: 0.8629 (1114 detections,  530 groundtruth, 489 non difficult)
horse - AP: 0.8406 (980 detections,  395 groundtruth, 348 non difficult)
motorbike - AP: 0.8002 (1157 detections,  369 groundtruth, 325 non difficult)
person - AP: 0.7899 (8977 detections,  5227 groundtruth, 4528 non difficult)
pottedplant - AP: 0.4819 (1579 detections,  592 groundtruth, 480 non difficult)
sheep - AP: 0.7657 (802 detections,  311 groundtruth, 242 non difficult)
sofa - AP: 0.8188 (1622 detections,  396 groundtruth, 239 non difficult)
train - AP: 0.8668 (784 detections,  302 groundtruth, 282 non difficult)
tvmonitor - AP: 0.7561 (937 detections,  361 groundtruth, 308 non difficult)
Mean AP: 0.7691

Also I got the detections.json file. Thank you very much for your help!)

**Comment by lachlants** [comment]
Nice, looks to be working as expected. I'll close the issue now.
