### ISSUE TITLE
How to get class probability vectors?

### ISSUE THREAD

**Issue by Jusya** [lachlants/denet#4]
Hello) I would like to thank you for helping me with my first issue again) If it is possible for you to help me with the following question, then is it possible get something like softmax class probability vectors in the detectons.json. What I've already managed to do, is to modify denet_detect.cc like:

```
typedef std::tuple<float, float, float, float, float, npy_intp, npy_intp, float*> Instance;`

static float get_overlap_iou(const Instance& inst_a, const Instance& inst_b){
    float x0_a = std::get<1>(inst_a);
    float y0_a = std::get<2>(inst_a);
    float x1_a = std::get<3>(inst_a);
    float y1_a = std::get<4>(inst_a);

    float x0_b = std::get<1>(inst_b);
    float y0_b = std::get<2>(inst_b);
    float x1_b = std::get<3>(inst_b);
    float y1_b = std::get<4>(inst_b);

    float dx = std::max(0.0f, std::min(x1_a, x1_b) - std::max(x0_a, x0_b));
    float dy = std::max(0.0f, std::min(y1_a, y1_b) - std::max(y0_a, y0_b));
    float area_intersect = dx*dy;
    float area_a = (x1_a - x0_a)*(y1_a - y0_a);
    float area_b = (x1_b - x0_b)*(y1_b - y0_b);
    float area_union = area_a + area_b - area_intersect;
    return area_intersect / area_union;
};

static PyObject* build_detections_nms(PyObject *self, PyObject *args) {

    //get args
    float pr_threshold; 
    float nms_threshold; 
    PyObject* det_obj; //ndarray
    PyObject* bbox_obj; //ndarray
    PyObject* bbox_num; //list of int
    if (!PyArg_ParseTuple(args, "ffOOO", &pr_threshold, &nms_threshold, &det_obj, &bbox_obj, &bbox_num))
        return NULL;

    PyArrayObject* det_pr = (PyArrayObject*)PyArray_FROM_OTF(det_obj, NPY_FLOAT, NPY_IN_ARRAY);
    if (det_pr == NULL)
        return NULL;

    PyArrayObject* bbox = (PyArrayObject*)PyArray_FROM_OTF(bbox_obj, NPY_FLOAT, NPY_IN_ARRAY);
    if (bbox == NULL)
        return NULL;

    float log_pr_threshold = std::log(pr_threshold);
    npy_intp batch_size = PyArray_DIM(det_pr, 0);
    npy_intp class_num = PyArray_DIM(det_pr, 1) - 1;
    npy_intp sample_num = PyArray_DIM(det_pr, 2);

    PyObject* det_lists = PyList_New(0);
    for(npy_intp b=0; b < batch_size; b++){

        long batch_bbox_num = PyLong_AS_LONG(PyList_GET_ITEM(bbox_num, b));
        PyObject* batch_dets = PyList_New(0);
        size_t before_nms=0, after_nms=0;
        for(npy_intp cls=0; cls < class_num; cls++){

            std::vector<Instance> instances;
            for(npy_intp j=0; (j < sample_num) && ((j*sample_num) < batch_bbox_num); j++){
                for(npy_intp i=0; (i < sample_num) && ((j*sample_num + i) < batch_bbox_num); i++){

                   float* sample_probs = new float[class_num + 1];
                    for(npy_intp cls1=0; cls1 < class_num + 1; cls1++){
                        float sample_log_pr = *(float*)PyArray_GETPTR4(det_pr, b, cls1, j, i);
                        float sample_prob = std::exp(sample_log_pr);
                        sample_probs[cls1] = sample_prob;
                    }

                    float log_pr = *(float*)PyArray_GETPTR4(det_pr, b, cls, j, i);
                    if (log_pr >= log_pr_threshold){
                        float* det_bbox = (float*)PyArray_GETPTR4(bbox, b, j, i, 0);
                        instances.push_back(Instance(log_pr, det_bbox[0], det_bbox[1], det_bbox[2], det_bbox[3], j, i, sample_probs));
                    }
                }
            }
            before_nms += instances.size();

            //run NMS
            std::vector<Instance> instances_nms;
            if ((nms_threshold > 0.0) && (nms_threshold < 1.0)){
                
                for(const Instance& inst_a: instances){
                    bool unique=true;
                    for(const Instance& inst_b : instances){
                        if ((std::get<0>(inst_a) < std::get<0>(inst_b)) && (get_overlap_iou(inst_a, inst_b) > nms_threshold)){
                            unique = false;
                            break;
                        }
                    }
                    if (unique)
                        instances_nms.push_back(inst_a);
                };
                
            } else {
                instances_nms = instances;
            }
            after_nms += instances_nms.size();

            for(const Instance& inst: instances_nms){
                **std::string probs_string = "";
                for(int i = 0; i < class_num + 1; i++){
                    probs_string += "f";
                }**
                PyObject* det = Py_BuildValue(("fi(ffff)"** + probs_string).c_str()**, std::exp(std::get<0>(inst)), cls, std::get<1>(inst), std::get<2>(inst), std::get<3>(inst), std::get<4>(inst), std::get<7>(inst));
                PyList_Append(batch_dets, det);
                Py_DECREF(det);
            }
        }
        // printf("%i - NMS before: %zu, after %zu\n", b, before_nms, after_nms);
        PyList_Append(det_lists, batch_dets);
        Py_DECREF(batch_dets);
    }

    Py_DECREF(det_pr);
    Py_DECREF(bbox);
    return det_lists;

}

static PyMethodDef methods[] = {
        {"build_detections_nms", build_detections_nms, METH_VARARGS, ""},
        {NULL, NULL, 0, NULL}
};

static struct PyModuleDef moduledef = {
    PyModuleDef_HEAD_INIT,
    "denet_detect",
    NULL,
    -1,
    methods,
    NULL,
    NULL,
    NULL,
    NULL
};

PyMODINIT_FUNC PyInit_denet_detect(void){
    import_array();
    PyObject *m = PyModule_Create(&moduledef);
    return m;
};

```

with assumption, that det_pr contains a softmax vector (is your case log_softmax vector) is your class probabilities vectors for detections and first 20 components of it denotes to PASCAL VOC classes and the last 21 component to class 'null' (and because it is log_softmax you need to compute exp before you get actual class probabilities). But when I write them into the detections.json I get:

{
      "meta": {
        "scale": [
          1.024,
          1.024
        ],
        "bbox": [
          [
            0.382,
            0.155,
            0.726,
            0.621
          ]
        ],
        "mirror": false,
        "image": {
          "fname": "/home/yulia/PycharmProjects/PASCAL VOC/VOC2007 test/VOC2007/JPEGImages/000008.jpg",
          "difficult": [
            false
          ],
          "bboxs": [
            [
              8,
              [
                191,
                15,
                363,
                248
              ]
            ]
          ]
        },
        "class": [
          8
        ],
        "offset": [
          0,
          -64
        ],
        "image_size": [
          500,
          375
        ]
      },
      "detections": [
        [
          0.3030449151992798,
          8,
          [
            0.0013727322220802307,
            0.5019946694374084,
            0.10281166434288025,
            0.864723265171051
          ],
          0.0,
          1.5514139955e-314,
          1.9035985662552932e+185,
          6.9532438905885e-310,
          3.079071413e-315,
          0.864723265171051,
          0.10281166434288025,
          0.5019946694374084,
          2.5e-323,
          4e-323,
          0.0013727322220802307,
          1.2e-322,
          2.846e-321,
          6.9365108328561e-310,
          4.15e-322,
          -1239.3887228797048,
          6.936529101712e-310,
          0.3030449151992798,
          6.93650252247864e-310,
          6.93651684831124e-310,
          4e-323
        ],
        [
          0.9998823404312134,
          8,
          [
            0.38018351793289185,
            0.17481878399848938,
            0.705095112323761,
            0.6256318092346191
          ],
          0.0,
          1.5514139955e-314,
          1.9035985662552932e+185,
          6.9532438905885e-310,
          3.079071413e-315,
          0.6256318092346191,
          0.705095112323761,
          0.17481878399848938,
          2.5e-323,
          4e-323,
          0.38018351793289185,
          1.2e-322,
          2.846e-321,
          6.9365108328561e-310,
          4.15e-322,
          -1239.3887228797048,
          6.936529101712e-310,
          0.9998823404312134,
          6.93650252247864e-310,
          6.93651684831124e-310,
          4e-323
        ],
        [
          0.08476103097200394,
          8,
          [
            0.27250778675079346,
            0.5628441572189331,
            0.6248316168785095,
            0.8794838190078735
          ],
          0.0,
          1.5514139955e-314,
          1.9035985662552932e+185,
          6.9532438905885e-310,
          3.079071413e-315,
          0.8794838190078735,
          0.6248316168785095,
          0.5628441572189331,
          2.5e-323,
          4e-323,
          0.27250778675079346,
          1.2e-322,
          2.846e-321,
          6.9365108328561e-310,
          4.15e-322,
          -1239.3887228797048,
          6.936529101712e-310,
          0.08476103097200394,
          6.93650252247864e-310,
          6.93651684831124e-310,
          4e-323
        ],
        [
          0.0431208536028862,
          11,
          [
            -0.0007366538047790527,
            0.5240722894668579,
            0.1058601438999176,
            0.8655219078063965
          ],
          0.0,
          1.595616974e-314,
          1.9035985662552932e+185,
          6.9532438905885e-310,
          2.92780701e-315,
          0.8655219078063965,
          0.1058601438999176,
          0.5240722894668579,
          2.5e-323,
          5.4e-323,
          -0.0007366538047790527,
          1.2e-322,
          2.846e-321,
          6.9365108328561e-310,
          4.15e-322,
          -1239.3887228797048,
          6.936529101712e-310,
          0.0431208536028862,
          6.93650252247864e-310,
          6.93651684831124e-310,
          4e-323
        ],
        [
          0.05106999725103378,
          14,
          [
            -0.00273049995303154,
            0.5344655513763428,
            0.09292234480381012,
            0.8737093210220337
          ],
          0.0,
          1.5957156223e-314,
          1.9035985662552932e+185,
          6.9532438905885e-310,
          2.927773413e-315,
          0.8737093210220337,
          0.09292234480381012,
          0.5344655513763428,
          2.5e-323,
          7e-323,
          -0.00273049995303154,
          1.2e-322,
          2.846e-321,
          6.9365108328561e-310,
          4.15e-322,
          -1239.3887228797048,
          6.936529101712e-310,
          0.05106999725103378,
          6.93650252247864e-310,
          6.93651684831124e-310,
          4e-323
        ],
        [
          0.04868819937109947,
          17,
          [
            0.0009535849094390869,
            0.504220724105835,
            0.10251316428184509,
            0.8658108711242676
          ],
          0.0,
          1.595068334e-314,
          1.9035985662552932e+185,
          6.9532438905885e-310,
          3.081500555e-315,
          0.8658108711242676,
          0.10251316428184509,
          0.504220724105835,
          2.5e-323,
          8.4e-323,
          0.0009535849094390869,
          1.2e-322,
          2.846e-321,
          6.9365108328561e-310,
          4.15e-322,
          -1239.3887228797048,
          6.936529101712e-310,
          0.04868819937109947,
          6.93650252247864e-310,
          6.93651684831124e-310,
          4e-323
        ],
        [
          0.7103296518325806,
          17,
          [
            0.8675391674041748,
            0.5496058464050293,
            1.0043929815292358,
            0.8745944499969482
          ],
          0.0,
          1.595068334e-314,
          1.9035985662552932e+185,
          6.9532438905885e-310,
          3.081500555e-315,
          0.8745944499969482,
          1.0043929815292358,
          0.5496058464050293,
          2.5e-323,
          8.4e-323,
          0.8675391674041748,
          1.2e-322,
          2.846e-321,
          6.9365108328561e-310,
          4.15e-322,
          -1239.3887228797048,
          6.936529101712e-310,
          0.7103296518325806,
          6.93650252247864e-310,
          6.93651684831124e-310,
          4e-323
        ]
      ]
    },

So I think I've missed something, and what I'm trying to work with isn't class probabilities at all. It wolud be great, if you could give me a hint, what I understand wrong) Thank you in advance)

**Comment by lachlants** [comment]
Hello, 

Pretty sure the problem is in the `Py_BuildValue` call, you cannot pass a float pointer to the function. You need to construct a tuple and fill it with the values  e.g. 

```c
PyObject* pr_tuple = PyTuple_New();
float* pr = std::get<7>(inst);
for(int i=0; i < (class_num+1); i++) {
    PyTuple_SET_ITEM(pr_tuple, i, Py_BuildValue("f", pr[i]));
}
PyObject* det = Py_BuildValue(("fi(ffff)O", std::exp(std::get<0>(inst)), cls, std::get<1>(inst), std::get<2>(inst), std::get<3>(inst), std::get<4>(inst), pr_tuple);
//clean up 
```

**However** a much easier way would be to return the j and i index from the C code e.g. 

`PyObject* det = Py_BuildValue(("fi(ffff)ii", std::exp(std::get<0>(inst)), cls, std::get<1>(inst), std::get<2>(inst), std::get<3>(inst), std::get<4>(inst), std::get<5>(inst), std::get<6>(inst));`

Then in the python code (denet_detect.py) extract the probablility vector e.g. 

```python
for b, detlist in enumerate(detlists):
    detlist_with_clspr=[]
    for pr,cls,bbox,j,i in detlist:
        clspr = numpy.exp(det_pr[b,:,j,i]).tolist()
        detlist_with_clspr.append([pr,cls,bbox,clspr])
    results.append({"detections":detlist_with_clspr, "meta":data_m[i]})
```

**Comment by Jusya** [comment]
That's great, I got the probability vectors with your second suggestion. Thank you for your help, that's exactly what I need)
